create table "public"."software" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "description" text not null,
    "upvotes" integer not null default 0
);


alter table "public"."software" enable row level security;

create table "public"."users" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "username" character varying not null
);


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX software_pkey ON public.software USING btree (id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

CREATE UNIQUE INDEX users_username_key ON public.users USING btree (username);

alter table "public"."software" add constraint "software_pkey" PRIMARY KEY using index "software_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."users" add constraint "users_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."users" validate constraint "users_id_fkey";

alter table "public"."users" add constraint "users_username_key" UNIQUE using index "users_username_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.users (id, username, email)
  values (new.id, new.raw_user_meta_data ->> 'username', new.email);
  return new;
end;
$function$
;

grant delete on table "public"."software" to "anon";

grant insert on table "public"."software" to "anon";

grant references on table "public"."software" to "anon";

grant select on table "public"."software" to "anon";

grant trigger on table "public"."software" to "anon";

grant truncate on table "public"."software" to "anon";

grant update on table "public"."software" to "anon";

grant delete on table "public"."software" to "authenticated";

grant insert on table "public"."software" to "authenticated";

grant references on table "public"."software" to "authenticated";

grant select on table "public"."software" to "authenticated";

grant trigger on table "public"."software" to "authenticated";

grant truncate on table "public"."software" to "authenticated";

grant update on table "public"."software" to "authenticated";

grant delete on table "public"."software" to "service_role";

grant insert on table "public"."software" to "service_role";

grant references on table "public"."software" to "service_role";

grant select on table "public"."software" to "service_role";

grant trigger on table "public"."software" to "service_role";

grant truncate on table "public"."software" to "service_role";

grant update on table "public"."software" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";


