ALTER TABLE "public"."software" ADD COLUMN "links" jsonb NOT NULL DEFAULT '{}';

-- Optional installation instructions (1:1 with software)
CREATE TABLE public.installation_instructions (
  software_id BIGINT PRIMARY KEY,                -- Same as software.id
  windows TEXT NOT NULL,                         -- Windows installation text
  macos TEXT NOT NULL,                           -- macOS installation text
  linux TEXT NOT NULL,                           -- Linux installation text
  CONSTRAINT fk_installation_software
    FOREIGN KEY (software_id)
    REFERENCES public.software(id)
    ON DELETE CASCADE
);

-- Features (1:N with software)
CREATE TABLE public.features (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  software_id BIGINT NOT NULL,                   -- FK to software
  title TEXT NOT NULL,                           -- Feature title
  description TEXT NOT NULL,                     -- Feature description
  CONSTRAINT fk_features_software
    FOREIGN KEY (software_id)
    REFERENCES public.software(id)
    ON DELETE CASCADE
);

-- User reviews (1:N with software)
CREATE TABLE public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  software_id BIGINT NOT NULL,                   -- FK to software
  username TEXT NOT NULL,                        -- Review author
  date TIMESTAMPTZ NOT NULL,                     -- When the review was written
  comment TEXT NOT NULL,                         -- Review content
  is_upvote BOOLEAN NOT NULL,                    -- True if upvote, false if downvote
  CONSTRAINT fk_reviews_software
    FOREIGN KEY (software_id)
    REFERENCES public.software(id)
    ON DELETE CASCADE
);
